services:
    Mhpdigital\CrossTenantSecurity\Repository\CrossTenantRepositoryFactory:
        arguments:
            $doctrine: '@doctrine'
            $tokenStorage: '@security.token_storage'
            $roleHierarchy: '@security.role_hierarchy'
            $requestStack: '@request_stack'
